### ISSUE TITLE
请教一下库函数的调用是如何分析和处理的？

### ISSUE THREAD

**Issue by Ingsuifon** [i-Pear/CSC2020-NEU-Q29tcGlsZXI-#1]
我目前只在AsmHelper里看到和库函数相关的内容，里面大致为保存状态、调用库函数、恢复状态，我想请问一下参数是在哪里被传递的？

**Comment by i-Pear** [comment]
函数调用的相关代码在Assembly.cpp Line774，前半部分是内建函数的特判。860行起是非内建函数的跳转，892行起是参数的复制过程。

**Comment by Ingsuifon** [comment]
谢谢！
